<?php

namespace Wonka\CinemaBundle\Entity;

use Doctrine\ORM\EntityRepository;
 
/**
* FilmRepository
* 
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class FilmRepository extends EntityRepository
{
    public function getOneBySlug($slug)
    {
        $query = $this->getEntityManager()
                ->createQuery(
                        'SELECT f FROM WonkaCinemaBundle:Film f
                        WHERE f.slug LIKE :slug'
                )->setParameters(array(
                    'slug'  => $slug,
                ))->setMaxResults(1);
        try {
            return $query->getOneOrNullResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    public function getSheduleByCinemaIdAndHallId($cinema_id, $hall_id = null)
    {
        $query_parameters = array(
            'cinema_id' => $cinema_id,
            'time'      => date('Y-m-d H:i:s'),
        );
        $hall_cond = null;
        if (intval($hall_id) > 0) {
            $hall_cond = ' AND (h.id = :hall_id)';
            $query_parameters['hall_id'] = $hall_id;
        }
        $query = $this->getEntityManager()
                ->createQuery(
                        'SELECT f, s, h FROM WonkaCinemaBundle:Film f
                        INNER JOIN f.sessions s
                        INNER JOIN s.hall h
                        INNER JOIN h.cinema c
                        WHERE (c.id LIKE :cinema_id)
                        AND (s.time > :time)
                        '.$hall_cond.'
                        ORDER BY s.time ASC'
                )->setParameters($query_parameters);
        try {
            return $query->getArrayResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
