<?php

namespace Wonka\CinemaBundle\Entity;

use Doctrine\ORM\EntityRepository;
 
/**
* SessionRepository
* 
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class SessionRepository extends EntityRepository
{
    public function getOneByIdJoinAll($id)
    {
        $query = $this->getEntityManager()
                ->createQuery(
                        'SELECT s, h, c, f, t FROM WonkaCinemaBundle:Session s
                        LEFT JOIN s.tickets t
                        INNER JOIN s.hall h
                        INNER JOIN h.cinema c
                        INNER JOIN s.film f
                        WHERE (s.id LIKE :id)'
                )->setParameters(array(
                    'id' => $id,
                ));
        try {
            return $query->getOneOrNullResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    public function getOneByReserveId($id)
    {
        $time = date('Y-m-d H:i:s', strtotime(date('Y-m-d H:i:s').' + 1 hours'));
        $query = $this->getEntityManager()
                ->createQuery(
                        'SELECT s FROM WonkaCinemaBundle:Session s
                        INNER JOIN s.tickets t
                        INNER JOIN t.reserve r
                        WHERE (r.id = :id)
                        AND (s.time > :time)'
                )->setParameters(array(
                    'id'    => $id,
                    'time'  => $time,
                ))->setMaxResults(1);
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
